# Generated by Django 3.2.9 on 2022-10-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
