# Generated by Django 5.2.11 on 2026-02-19 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_change", "Password Change"),
                            ("permission_change", "Permission Change"),
                            ("export", "Data Export"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Model name, e.g. 'Transaction'", max_length=50
                    ),
                ),
                ("resource_id", models.CharField(blank=True, max_length=50)),
                ("resource_repr", models.CharField(blank=True, max_length=255)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON of changed fields: {field: {old: x, new: y}}",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "timestamp"],
                        name="audit_audit_company_d34f9e_idx",
                    ),
                    models.Index(
                        fields=["company", "resource_type"],
                        name="audit_audit_company_1c4a94_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="audit_audit_actor_i_ebf1ec_idx",
                    ),
                ],
            },
        ),
    ]
