# Generated by Django 3.2.9 on 2021-11-03 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=16)),
                ('bank', models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='GT Bank', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDepositRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=500)),
                ('bank', models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='GT Bank', max_length=100)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requesting', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requesting', to='fnet_api.customer')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnet_api.fnetadmin')),
            ],
        ),
    ]
