# Generated by Django 3.2.9 on 2022-07-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawReference',
        ),
    ]
