# Generated by Django 3.2.9 on 2022-01-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='additional_payment',
            new_name='additional_payments',
        ),
    ]
