# Generated by Django 3.2.9 on 2021-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='request_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(max_length=15),
        ),
    ]
