# Generated by Django 3.2.9 on 2021-11-05 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='guarantor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
