# Generated by Django 3.2.9 on 2021-11-21 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankPayment',
            new_name='CashAtPayments',
        ),
    ]
