# Generated by Django 3.2.9 on 2022-01-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
