# Generated by Django 3.2.9 on 2021-11-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('reference_id', models.CharField(max_length=50)),
                ('date_withdrew', models.DateField(default=django.utils.timezone.now)),
                ('time_withdrew', models.TimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='left_with_phone',
            field=models.CharField(default='Bank Teller', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WithdrawFerence',
        ),
    ]
