# Generated by Django 3.2.9 on 2021-12-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='reference',
            new_name='transaction_id',
        ),
    ]
