# Generated by Django 3.2.9 on 2021-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdepositrequests',
            name='has_closed_request',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='deposit_request',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
