# Generated by Django 3.2.9 on 2022-01-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0003_mypayments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
