# Generated by Django 3.2.9 on 2022-07-13 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0003_delete_paymentatbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawreference',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='withdrawreference',
            name='date_withdrew',
        ),
        migrations.RemoveField(
            model_name='withdrawreference',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='withdrawreference',
            name='time_withdrew',
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_100',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_200',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='d_50',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='teller_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='teller_phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='time_added',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='withdrawreference',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='withdrawreference',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
