# Generated by Django 3.2.9 on 2021-11-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0003_rename_bankpayment_cashatpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashatpayments',
            old_name='bank',
            new_name='location',
        ),
    ]
