# Generated by Django 3.2.9 on 2021-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0003_auto_20211121_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='date_paid',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='time_paid',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawreference',
            name='date_withdrew',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawreference',
            name='time_withdrew',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
