# Generated by Django 3.2.9 on 2022-01-20 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0003_rename_additional_payment_payments_additional_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='MyPayments',
        ),
    ]
