# Generated by Django 3.2.9 on 2021-11-04 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0003_customerwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[('Bank Payment', 'Bank Payment'), ('Momo Payment', 'Momo Payment'), ('Momo pay Payment', 'Momo pay Payment'), ('Agent to Agent', 'Agent to Agent'), ('Bank Payment', 'Bank Payment'), ('Cash left @', 'Cash left @')], max_length=30)),
                ('cash_at_location', models.CharField(blank=True, choices=[('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA')], max_length=30)),
                ('amount', models.CharField(max_length=500)),
                ('payment_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
