# Generated by Django 3.2.9 on 2021-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0003_rename_reference_payments_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounts',
            name='account_name',
            field=models.CharField(default='Fnet User', max_length=100),
            preserve_default=False,
        ),
    ]
