# Generated by Django 3.2.9 on 2022-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0004_auto_20220713_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawreference',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawreference',
            name='time_added',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
