# Generated by Django 3.2.9 on 2021-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='payments',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Bank Payment', 'Bank Payment'), ('Momo Payment', 'Momo Payment'), ('Momo pay Payment', 'Momo pay Payment'), ('Agent to Agent', 'Agent to Agent'), ('Bank Payment', 'Bank Payment'), ('Cash left @', 'Cash left @')], max_length=30),
        ),
    ]
