# Generated by Django 3.2.9 on 2021-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0004_auto_20211109_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='has_closed_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='Access Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='GT Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='bank',
            field=models.CharField(blank=True, choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Select mode of payment', 'Select mode of payment'), ('Bank Payment', 'Bank Payment'), ('Momo Payment', 'Momo Payment'), ('Momo pay Payment', 'Momo pay Payment'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @')], max_length=30),
        ),
    ]
