# Generated by Django 3.2.9 on 2021-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0004_customeraccounts_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdepositrequests',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agentdepositrequests',
            name='mobile_money',
            field=models.CharField(blank=True, choices=[('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='request_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Banks', 'Banks')], default='Physical Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrequestdeposit',
            name='request_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Banks', 'Banks')], default='Physical Cash', max_length=100),
        ),
    ]
