# Generated by Django 3.2.9 on 2021-11-10 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0005_auto_20211110_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
