# Generated by Django 3.2.9 on 2022-07-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0005_auto_20220729_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='expensesrequest',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='mypayments',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='otp',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='paymentatbank',
            name='app_version',
            field=models.CharField(default='4', max_length=5),
        ),
    ]
