# Generated by Django 3.2.9 on 2021-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0005_alter_cashatpayments_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='cash_at_location',
            field=models.CharField(blank=True, choices=[('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA')], default='', max_length=30),
        ),
    ]
