# Generated by Django 3.2.9 on 2021-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0005_auto_20211105_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='amount',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='customer',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
