# Generated by Django 3.2.9 on 2021-11-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0005_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank',
        ),
    ]
