# Generated by Django 3.2.9 on 2022-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0006_auto_20220729_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='expensesrequest',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='otp',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='paymentatbank',
            name='app_version',
            field=models.CharField(max_length=5),
        ),
    ]
