# Generated by Django 3.2.9 on 2021-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0006_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='has_closed_today',
        ),
        migrations.AddField(
            model_name='agentdepositrequests',
            name='has_closed_today',
            field=models.BooleanField(default=False),
        ),
    ]
