# Generated by Django 3.2.9 on 2021-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0006_alter_payments_cash_at_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='bank',
            field=models.CharField(blank=True, choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='', max_length=50),
        ),
    ]
