# Generated by Django 3.2.9 on 2021-11-07 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0006_auto_20211105_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccountsCompletedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_cash', models.IntegerField()),
                ('mtn_eCash', models.IntegerField()),
                ('vodafone_eCash', models.IntegerField()),
                ('airtel_tigo_eCash', models.IntegerField()),
                ('ecobank_eCash', models.IntegerField()),
                ('calbank_eCash', models.IntegerField()),
                ('fidelity_eCash', models.IntegerField()),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAccountsStartedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_cash', models.IntegerField()),
                ('mtn_eCash', models.IntegerField()),
                ('vodafone_eCash', models.IntegerField()),
                ('airtel_tigo_eCash', models.IntegerField()),
                ('ecobank_eCash', models.IntegerField()),
                ('calbank_eCash', models.IntegerField()),
                ('fidelity_eCash', models.IntegerField()),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FNetAdmin',
        ),
    ]
