# Generated by Django 3.2.9 on 2021-12-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0006_alter_agentdepositrequests_request_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='mobile_money',
            field=models.CharField(blank=True, choices=[('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='request_option',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Banks', 'Banks')], default='', max_length=100),
        ),
    ]
