# Generated by Django 3.2.9 on 2021-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0007_auto_20211207_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='mobile_money',
            field=models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='', max_length=20),
        ),
    ]
