# Generated by Django 3.2.9 on 2021-11-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0007_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='GT Bank', max_length=100),
        ),
    ]
