# Generated by Django 3.2.9 on 2021-11-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0008_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdepositrequests',
            name='bank',
        ),
        migrations.AddField(
            model_name='agentdepositrequests',
            name='request_option',
            field=models.CharField(choices=[('Physical Cash', 'Physical Cash'), ('Mtn Ecash', 'Mtn Ecash'), ('Vodafone Ecash', 'Vodafone Ecash'), ('AirtelTigo Ecash', 'AirtelTigo Ecash'), ('Ecobank Ecash', 'Ecobank Ecash'), ('Calbank Ecash', 'Calbank Ecash'), ('Fidelity Ecash', 'Fidelity Ecash')], default='Physical Cash', max_length=100),
        ),
    ]
