# Generated by Django 3.2.9 on 2021-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0008_auto_20211111_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdepositrequests',
            name='has_closed_today',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_action',
            field=models.CharField(choices=[('Select payment action', 'Select payment action'), ('Close Payment', 'Close Payment')], default='Close Payment', max_length=50),
        ),
    ]
