# Generated by Django 3.2.9 on 2021-11-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0008_auto_20211122_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='', max_length=50)),
                ('amount', models.CharField(blank=True, max_length=500)),
                ('request_option', models.CharField(choices=[('Physical Cash', 'Physical Cash'), ('Mtn Ecash', 'Mtn Ecash'), ('Vodafone Ecash', 'Vodafone Ecash'), ('AirtelTigo Ecash', 'AirtelTigo Ecash'), ('Ecobank Ecash', 'Ecobank Ecash'), ('Calbank Ecash', 'Calbank Ecash'), ('Fidelity Ecash', 'Fidelity Ecash')], default='Physical Cash', max_length=100)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('time_requested', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
