# Generated by Django 3.2.9 on 2021-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0008_alter_agentdepositrequests_mobile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdepositrequests',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
