# Generated by Django 3.2.9 on 2021-11-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0008_customer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='guarantor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fnet_api.fnetadmin'),
        ),
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='Access Bank', max_length=100),
        ),
    ]
