# Generated by Django 3.2.9 on 2021-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0009_customerrequestdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequestdeposit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrequestdeposit',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
