# Generated by Django 3.2.9 on 2021-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0009_auto_20211105_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='customer',
            field=models.CharField(max_length=30),
        ),
    ]
