# Generated by Django 3.2.9 on 2022-01-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0009_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Something',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
