# Generated by Django 3.2.9 on 2022-08-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0010_customerpaymentatbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_from_customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
