# Generated by Django 3.2.9 on 2021-11-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0010_auto_20211127_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequestdeposit',
            name='bank',
        ),
    ]
