# Generated by Django 3.2.9 on 2022-01-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0010_auto_20220128_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(blank=True, max_length=200)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('customer', models.CharField(blank='', default='', max_length=100)),
                ('customer_request_slug', models.CharField(blank=True, max_length=100)),
                ('cash_deposit_request_slug', models.CharField(blank=True, max_length=100)),
                ('bank_deposit_request_slug', models.CharField(blank=True, max_length=100)),
                ('payment_slug', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_receiving_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
