# Generated by Django 3.2.9 on 2022-08-10 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0011_notifications_notification_from_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='de_administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_to_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddedToApprovedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnet_api.mypayments')),
            ],
        ),
        migrations.CreateModel(
            name='AddedToApprovedDeposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('bank_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnet_api.bankdeposit')),
            ],
        ),
    ]
