# Generated by Django 3.2.9 on 2022-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0011_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20),
        ),
    ]
