# Generated by Django 3.2.9 on 2021-12-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0011_remove_customerrequestdeposit_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccountscompletedwith',
            name='eCash',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='adminaccountscompletedwith',
            name='physical_cash',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='adminaccountsstartedwith',
            name='eCash',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='adminaccountsstartedwith',
            name='physical_cash',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='cashatpayments',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='customerrequestdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='withdrawreference',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
