# Generated by Django 3.2.9 on 2021-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0012_alter_agentdepositrequests_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='mobile_money',
            field=models.CharField(blank=True, choices=[('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='', max_length=20),
        ),
    ]
