# Generated by Django 3.2.9 on 2022-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0013_alter_notifications_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='item_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
