# Generated by Django 3.2.9 on 2022-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0013_auto_20220912_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='network',
            field=models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('Tigo', 'Tigo'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='Select Network', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='type',
            field=models.CharField(blank=True, choices=[('Loading', 'Loading'), ('Direct', 'Direct'), ('Agent to Agent', 'Agent to Agent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='network',
            field=models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('Tigo', 'Tigo'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='Select Network', max_length=20),
        ),
    ]
