# Generated by Django 3.2.9 on 2021-12-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0014_userflags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='mobile_money',
            field=models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='Select Network', max_length=20),
        ),
    ]
