# Generated by Django 3.2.9 on 2022-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0014_notifications_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
