# Generated by Django 3.2.9 on 2021-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0015_alter_agentdepositrequests_mobile_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='account_number',
            field=models.TextField(blank=True),
        ),
    ]
