# Generated by Django 3.2.9 on 2022-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0015_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
