# Generated by Django 3.2.9 on 2022-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0015_notifications_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_trigger',
            field=models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=100),
        ),
    ]
