# Generated by Django 3.2.9 on 2022-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0016_reports_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='title',
        ),
    ]
