# Generated by Django 3.2.9 on 2021-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0016_alter_agentdepositrequests_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdepositrequests',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
