# Generated by Django 3.2.9 on 2022-01-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0016_notifications_notification_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayments',
            name='mode_of_payment1',
            field=models.CharField(blank=True, choices=[('Select mode of payment', 'Select mode of payment'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @'), ('Own Accounts', 'Own Accounts'), ('Company Accounts', 'Company Accounts')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='mode_of_payment2',
            field=models.CharField(blank=True, choices=[('Select mode of payment', 'Select mode of payment'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @'), ('Own Accounts', 'Own Accounts'), ('Company Accounts', 'Company Accounts')], max_length=30),
        ),
    ]
