# Generated by Django 3.2.9 on 2021-12-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0018_auto_20211227_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerwithdrawal',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customerwithdrawal',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='action',
        ),
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='request_status',
        ),
        migrations.CreateModel(
            name='MobileMoneyWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=30)),
                ('network', models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], default='Select Network', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('MomoPay', 'MomoPay'), ('Cash Out', 'Cash Out'), ('Agent to Agent', 'Agent to Agent')], default='', max_length=30)),
                ('id_type', models.CharField(choices=[('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id')], max_length=30)),
                ('id_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('time_requested', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
