# Generated by Django 3.2.9 on 2022-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0019_auto_20220212_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesrequest',
            name='slug',
        ),
    ]
