# Generated by Django 3.2.9 on 2021-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0019_auto_20211228_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='date_requested',
            new_name='date_deposited',
        ),
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='time_requested',
            new_name='time_deposited',
        ),
        migrations.RenameField(
            model_name='mobilemoneywithdraw',
            old_name='date_requested',
            new_name='date_of_withdrawal',
        ),
        migrations.RenameField(
            model_name='mobilemoneywithdraw',
            old_name='time_requested',
            new_name='time_of_withdrawal',
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
