# Generated by Django 3.2.9 on 2022-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0020_groupmessage_privateusermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateusermessage',
            name='private_chat_id',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
