# Generated by Django 3.2.9 on 2022-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0021_auto_20220217_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayments',
            name='payment_action',
            field=models.CharField(choices=[('Select payment action', 'Select payment action'), ('Not Closed', 'Not Closed'), ('Close Payment', 'Close Payment')], default='Close Payment', max_length=50),
        ),
    ]
