# Generated by Django 3.2.9 on 2022-09-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0021_alter_privateusermessage_private_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group_users',
        ),
    ]
