# Generated by Django 3.2.9 on 2022-02-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0022_alter_mypayments_payment_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
