# Generated by Django 3.2.9 on 2022-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0022_remove_groupmessage_group_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
