# Generated by Django 3.2.9 on 2022-02-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0023_auto_20220221_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='depositor_name',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id')], default='Passport', max_length=50),
        ),
    ]
