# Generated by Django 3.2.9 on 2022-09-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0023_privatechatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateusermessage',
            name='private_chat_id2',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
