# Generated by Django 3.2.9 on 2021-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0023_auto_20211229_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='digital_address',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
