# Generated by Django 3.2.9 on 2021-12-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0024_alter_customer_digital_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='agent_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='charges',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='mtn_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='agent_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='charges',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='mtn_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
