# Generated by Django 3.2.9 on 2022-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0024_auto_20220221_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwithdrawal',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('ATM', 'ATM')], default='Passport', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('ATM', 'ATM')], default='Passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='type',
            field=models.CharField(choices=[('MomoPay', 'MomoPay'), ('Cash Out', 'Cash Out'), ('Agent to Agent', 'Agent to Agent')], default='Cash Out', max_length=30),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('ATM', 'ATM')], max_length=30),
        ),
    ]
