# Generated by Django 3.2.9 on 2021-12-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0025_auto_20211230_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='mtn_commission',
        ),
    ]
