# Generated by Django 3.2.9 on 2022-03-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0025_auto_20220304_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerwithdrawal',
            name='type',
        ),
    ]
