# Generated by Django 3.2.9 on 2022-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0026_auto_20220926_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnetprivateusermessage',
            name='isSender',
            field=models.BooleanField(default=False),
        ),
    ]
