# Generated by Django 3.2.9 on 2021-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0026_remove_mobilemoneydeposit_mtn_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
