# Generated by Django 3.2.9 on 2021-12-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0027_auto_20211230_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
