# Generated by Django 3.2.9 on 2022-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0028_customerwithdrawal_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('Cheque', 'Cheque'), ('Atm Phone', 'Atm Phone')], default='Passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('Cheque', 'Cheque'), ('Atm Phone', 'Atm Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id'), ('Cheque', 'Cheque'), ('Atm Phone', 'Atm Phone')], max_length=30),
        ),
    ]
