# Generated by Django 3.2.9 on 2022-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0028_fnetprivateusermessage_isreceiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypayments',
            name='payment_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mypayments',
            name='payment_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
