# Generated by Django 3.2.9 on 2022-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0029_auto_20220427_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='depositor_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
