# Generated by Django 3.2.9 on 2021-12-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0029_auto_20211230_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermobilemoneyaccountsclosed',
            old_name='mtn_physical',
            new_name='physical',
        ),
        migrations.RenameField(
            model_name='usermobilemoneyaccountsstarted',
            old_name='mtn_physical',
            new_name='physical',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsclosed',
            name='physical_total',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsclosed',
            name='tigoairtel_physical',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsclosed',
            name='vodafone_physical',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsstarted',
            name='physical_total',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsstarted',
            name='tigoairtel_physical',
        ),
        migrations.RemoveField(
            model_name='usermobilemoneyaccountsstarted',
            name='vodafone_physical',
        ),
    ]
