# Generated by Django 3.2.9 on 2022-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0030_auto_20220427_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='by_month',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
