# Generated by Django 3.2.9 on 2022-09-29 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0030_auto_20220928_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocustomerredeempoints',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addtocustomerredeempoints',
            name='redeem_option',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('Express Accounts', 'Express Accounts'), ('Airtime', 'Airtime'), ('Melcom Coupon', 'Melcom Coupon')], default='Airtime', max_length=100),
        ),
    ]
