# Generated by Django 3.2.9 on 2022-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0030_auto_20211231_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='cash_out_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
