# Generated by Django 3.2.9 on 2022-01-08 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0031_mobilemoneywithdraw_cash_out_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mtn_ecash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tigoairtel_ecash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('vodafone_ecash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ecash_total', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('time_posted', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
