# Generated by Django 3.2.9 on 2022-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0031_bankdeposit_by_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='by_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
