# Generated by Django 3.2.9 on 2022-09-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0032_auto_20220930_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refercustomer',
            name='agent',
        ),
    ]
