# Generated by Django 3.2.9 on 2022-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0032_alter_bankdeposit_by_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdeposit',
            old_name='by_month',
            new_name='deposited_month',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='deposited_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
