# Generated by Django 3.2.9 on 2022-01-18 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0032_momorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='deposit_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='deposit_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='deposit_to_pay',
            field=models.CharField(blank=True, default='0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerrequestdeposit',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
