# Generated by Django 3.2.9 on 2022-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0033_auto_20220427_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Select Id Type', 'Select Id Type'), ('Cheque', 'Cheque'), ('Atm', 'Atm'), ('Phone', 'Phone')], default='Passport', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Cheque', 'Cheque'), ('Atm', 'Atm'), ('Phone', 'Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Cheque', 'Cheque'), ('Atm', 'Atm'), ('Phone', 'Phone')], max_length=30),
        ),
    ]
