# Generated by Django 3.2.9 on 2022-01-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0033_auto_20220118_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='deposit_paid',
            field=models.CharField(blank=True, choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='deposit_paid',
            field=models.CharField(blank=True, choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
    ]
