# Generated by Django 3.2.9 on 2022-01-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0034_auto_20220118_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='deposit_to_pay',
        ),
        migrations.AddField(
            model_name='payments',
            name='additional_payment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
