# Generated by Django 3.2.9 on 2022-09-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0034_alter_refercustomer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refercustomer',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
