# Generated by Django 3.2.9 on 2022-04-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0035_auto_20220427_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwithdrawal',
            name='withdrawal_type',
            field=models.CharField(choices=[('Select Withdrawal Type', 'Select Withdrawal Type'), ('Cheque', 'Cheque'), ('Atm', 'Atm'), ('Phone', 'Phone')], default='Cheque', max_length=120),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='id_type',
            field=models.CharField(choices=[('Select Id Type', 'Select Id Type'), ('Ghana Card', 'Ghana Card'), ('Passport', 'Passport'), ('Drivers License', 'Drivers License'), ('Voters Id', 'Voters Id')], max_length=20),
        ),
    ]
