# Generated by Django 3.2.9 on 2022-10-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0035_refercustomer_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='expensesrequest',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='mypayments',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='paymentatbank',
            name='app_version',
        ),
    ]
