# Generated by Django 3.2.9 on 2022-01-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0035_auto_20220119_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='bank',
            new_name='bank1',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='cash_at_location',
            new_name='cash_at_location1',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='mode_of_payment',
            new_name='mode_of_payment1',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='transaction_id',
            new_name='transaction_id1',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='additional_payment',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='payments',
            name='amount2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='payments',
            name='bank2',
            field=models.CharField(blank=True, choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], max_length=50),
        ),
        migrations.AddField(
            model_name='payments',
            name='cash_at_location2',
            field=models.CharField(blank=True, choices=[('Please select cash at location', 'Please select cash at location'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payments',
            name='mode_of_payment2',
            field=models.CharField(blank=True, choices=[('Select mode of payment', 'Select mode of payment'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @')], max_length=30),
        ),
        migrations.AddField(
            model_name='payments',
            name='transaction_id2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
