# Generated by Django 3.2.9 on 2022-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0036_auto_20220428_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='bank',
            field=models.CharField(blank=True, choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB'), ('Atwima Rural Bank', 'Atwima Rural Bank'), ('Omnibsic Bank', 'Omnibsic Bank'), ('Stanbic Bank', 'Stanbic Bank'), ('Absa Bank', 'Absa Bank'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Mtn', 'Mtn'), ('Vodafone', 'Vodafone'), ('Tigoairtel', 'Tigoairtel')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraccounts',
            name='bank',
            field=models.CharField(choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB'), ('Atwima Rural Bank', 'Atwima Rural Bank'), ('Omnibsic Bank', 'Omnibsic Bank'), ('Stanbic Bank', 'Stanbic Bank'), ('Absa Bank', 'Absa Bank'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Mtn', 'Mtn'), ('Vodafone', 'Vodafone'), ('Tigoairtel', 'Tigoairtel')], default='Access Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='bank',
            field=models.CharField(choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB'), ('Atwima Rural Bank', 'Atwima Rural Bank'), ('Omnibsic Bank', 'Omnibsic Bank'), ('Stanbic Bank', 'Stanbic Bank'), ('Absa Bank', 'Absa Bank'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Mtn', 'Mtn'), ('Vodafone', 'Vodafone'), ('Tigoairtel', 'Tigoairtel')], default='GT Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='bank1',
            field=models.CharField(blank=True, choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB'), ('Atwima Rural Bank', 'Atwima Rural Bank'), ('Omnibsic Bank', 'Omnibsic Bank'), ('Stanbic Bank', 'Stanbic Bank'), ('Absa Bank', 'Absa Bank'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Mtn', 'Mtn'), ('Vodafone', 'Vodafone'), ('Tigoairtel', 'Tigoairtel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='bank2',
            field=models.CharField(blank=True, choices=[('Select bank', 'Select bank'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB'), ('Atwima Rural Bank', 'Atwima Rural Bank'), ('Omnibsic Bank', 'Omnibsic Bank'), ('Stanbic Bank', 'Stanbic Bank'), ('Absa Bank', 'Absa Bank'), ('Universal Merchant Bank', 'Universal Merchant Bank'), ('Mtn', 'Mtn'), ('Vodafone', 'Vodafone'), ('Tigoairtel', 'Tigoairtel')], max_length=50),
        ),
    ]
