# Generated by Django 3.2.9 on 2022-01-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0036_auto_20220120_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='mode_of_payment1',
            field=models.CharField(blank=True, choices=[('Select mode of payment1', 'Select mode of payment1'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payments',
            name='mode_of_payment2',
            field=models.CharField(blank=True, choices=[('Select mode of payment2', 'Select mode of payment2'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @')], max_length=30),
        ),
    ]
