# Generated by Django 3.2.9 on 2022-01-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0037_auto_20220120_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='bank',
            field=models.CharField(blank=True, choices=[('Select bank1', 'Select bank1'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraccounts',
            name='bank',
            field=models.CharField(choices=[('Select bank1', 'Select bank1'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='Access Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerwithdrawal',
            name='bank',
            field=models.CharField(choices=[('Select bank1', 'Select bank1'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], default='GT Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='payments',
            name='bank1',
            field=models.CharField(blank=True, choices=[('Select bank1', 'Select bank1'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='bank2',
            field=models.CharField(blank=True, choices=[('Select bank2', 'Select bank2'), ('Access Bank', 'Access Bank'), ('Cal Bank', 'Cal Bank'), ('Fidelity Bank', 'Fidelity Bank'), ('Ecobank', 'Ecobank'), ('Pan Africa', 'Pan Africa'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('SGSSB', 'SGSSB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='cash_at_location1',
            field=models.CharField(blank=True, choices=[('Please select cash at location1', 'Please select cash at location1'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='payments',
            name='cash_at_location2',
            field=models.CharField(blank=True, choices=[('Please select cash at location2', 'Please select cash at location2'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA')], default='', max_length=40),
        ),
    ]
