# Generated by Django 3.2.9 on 2022-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0038_auto_20220120_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='reference1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payments',
            name='reference2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
