# Generated by Django 3.2.9 on 2022-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0038_auto_20221006_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='app_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expensesrequest',
            name='app_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='app_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='app_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='app_name',
            field=models.CharField(max_length=20),
        ),
    ]
