# Generated by Django 3.2.9 on 2023-03-06 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0040_auto_20221007_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypayments',
            name='cash_at_location1',
            field=models.CharField(blank=True, choices=[('Please select cash at location', 'Please select cash at location'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM TANOSO', 'MELCOM TANOSO'), ('MELCOM MANHYIA', 'MELCOM MANHYIA'), ('MELCOM TAFO', 'MELCOM TAFO'), ('MELCOM AHODWO', 'MELCOM AHODWO'), ('MELCOM ADUM', 'MELCOM ADUM'), ('MELCOM SUAME', 'MELCOM SUAME')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mypayments',
            name='cash_at_location2',
            field=models.CharField(blank=True, choices=[('Please select cash at location', 'Please select cash at location'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM TANOSO', 'MELCOM TANOSO'), ('MELCOM MANHYIA', 'MELCOM MANHYIA'), ('MELCOM TAFO', 'MELCOM TAFO'), ('MELCOM AHODWO', 'MELCOM AHODWO'), ('MELCOM ADUM', 'MELCOM ADUM'), ('MELCOM SUAME', 'MELCOM SUAME')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='CashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('requested_month', models.CharField(blank=True, default='', max_length=10)),
                ('requested_year', models.CharField(blank=True, default='', max_length=10)),
                ('time_requested', models.TimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requesting_cash', to=settings.AUTH_USER_MODEL)),
                ('agent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_delivering_cash', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
