# Generated by Django 3.2.9 on 2023-03-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0044_bankdeposit_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='app_version',
            field=models.CharField(max_length=10),
        ),
    ]
