# Generated by Django 3.2.9 on 2023-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0047_auto_20230413_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='agent_commission',
        ),
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='agent_commission',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='cash_out_commission',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='mtn_commission',
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='type',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Merchant', 'Merchant'), ('Agent', 'Agent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='type',
            field=models.CharField(blank=True, default='Cash Out', max_length=30),
        ),
    ]
