# Generated by Django 3.2.9 on 2023-07-18 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0049_auto_20230413_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateAgentPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(max_length=255, unique=True)),
                ('phone_model', models.CharField(max_length=55, unique=True)),
                ('phone_brand', models.CharField(max_length=55, unique=True)),
                ('finger_print', models.CharField(max_length=255, unique=True)),
                ('phone_authenticated', models.BooleanField(default=False)),
                ('date_authenticated', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
