# Generated by Django 3.2.9 on 2023-07-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fnet_api', '0050_authenticateagentphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumberWithPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.TextField(blank=True, max_length=17)),
                ('account_name', models.CharField(blank=True, default='', max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('date_deposited', models.DateField(auto_now_add=True)),
                ('time_deposited', models.TimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
