# Generated by Django 3.2.9 on 2023-07-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0052_accountnumberwithpoints_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnumberwithpoints',
            name='deposited_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='accountnumberwithpoints',
            name='deposited_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
