# Generated by Django 3.2.9 on 2023-07-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0054_agentandowneraccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecobank_youtube_video_link', models.CharField(max_length=500)),
                ('fidelity_youtube_video_link', models.CharField(max_length=500)),
                ('calbank_youtube_video_link', models.CharField(max_length=500)),
                ('mtn_youtube_video_link', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
