# Generated by Django 3.2.9 on 2023-07-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0056_auto_20230725_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercials',
            name='calbank_youtube_video_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commercials',
            name='fidelity_youtube_video_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commercials',
            name='mtn_youtube_video_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
