# Generated by Django 3.2.9 on 2023-07-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0057_auto_20230725_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercials',
            name='calbank_youtube_video_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commercials',
            name='ecobank_youtube_video_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercials',
            name='fidelity_youtube_video_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commercials',
            name='mtn_youtube_video_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
