# Generated by Django 3.2.9 on 2023-08-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0059_auto_20230812_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='app_version',
        ),
    ]
