# Generated by Django 3.2.9 on 2023-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0060_remove_bankdeposit_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='user_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
