# Generated by Django 3.2.9 on 2023-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0061_bankdeposit_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='user_location',
            field=models.CharField(max_length=255),
        ),
    ]
