# Generated by Django 3.2.9 on 2023-08-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0062_alter_bankdeposit_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='user_local_district',
            field=models.CharField(default='', max_length=255),
        ),
    ]
