# Generated by Django 3.2.9 on 2023-11-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0065_auto_20231126_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refercustomer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='digital_address',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='refercustomer',
            name='status',
        ),
    ]
