# Generated by Django 3.2.9 on 2023-11-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0066_auto_20231126_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercials',
            name='default_youtube_link',
            field=models.CharField(default='https://www.youtube.com/watch?v=fhIEp9iGEE4', max_length=255),
        ),
    ]
