# Generated by Django 3.2.9 on 2023-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0071_cashsupportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsupportrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cashsupportrequest',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
