# Generated by Django 3.2.9 on 2023-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0072_auto_20231128_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestRedeemPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('points', models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=19)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerpoints',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
