# Generated by Django 3.2.9 on 2023-11-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0073_auto_20231128_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequestRedeemPoints',
        ),
    ]
