# Generated by Django 3.2.9 on 2023-11-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0075_customerrequestredeempoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequestRedeemPoints',
        ),
    ]
