# Generated by Django 3.2.9 on 2023-11-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0076_delete_customerrequestredeempoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCustomerRequestToRedeemPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('redeemed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnet_api.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customerpoints',
            name='points_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AddToCustomerPoints',
        ),
    ]
