# Generated by Django 3.2.9 on 2023-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0077_auto_20231129_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocustomerrequesttoredeempoints',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
