# Generated by Django 3.2.9 on 2023-11-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0078_addtocustomerrequesttoredeempoints_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocustomerrequesttoredeempoints',
            name='customer',
        ),
    ]
