# Generated by Django 3.2.9 on 2023-11-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0079_remove_addtocustomerrequesttoredeempoints_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashSupport',
        ),
        migrations.DeleteModel(
            name='CashSupportBalance',
        ),
        migrations.DeleteModel(
            name='CashSupportRequest',
        ),
    ]
