# Generated by Django 3.2.9 on 2023-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0080_auto_20231130_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRedeemPointsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('points', models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=19)),
                ('redeemed', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddToCustomerRequestToRedeemPoints',
        ),
    ]
