# Generated by Django 3.2.9 on 2024-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0081_auto_20231204_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='user_local_district',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='user_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
