# Generated by Django 3.2.9 on 2024-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnet_api', '0082_auto_20240325_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, default='', upload_to='customerPics'),
        ),
    ]
