# Generated by Django 3.2.9 on 2023-09-21 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtn', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('express', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('ecobank', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('gtbank', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('calbank', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('fidelity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('over', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('shortage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('cash_left_at1', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at2', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at3', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at4', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at5', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at6', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at7', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at8', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at9', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('cash_left_at10', models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='HEAD OFFICE', max_length=100)),
                ('user1', models.CharField(blank=True, default='', max_length=20)),
                ('user2', models.CharField(blank=True, default='', max_length=20)),
                ('user3', models.CharField(blank=True, default='', max_length=20)),
                ('user4', models.CharField(blank=True, default='', max_length=20)),
                ('user5', models.CharField(blank=True, default='', max_length=20)),
                ('user6', models.CharField(blank=True, default='', max_length=20)),
                ('user7', models.CharField(blank=True, default='', max_length=20)),
                ('user8', models.CharField(blank=True, default='', max_length=20)),
                ('user9', models.CharField(blank=True, default='', max_length=20)),
                ('user10', models.CharField(blank=True, default='', max_length=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
