# Generated by Django 3.2.9 on 2023-09-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at1',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at10',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at2',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at3',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at4',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at5',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at6',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at7',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at8',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at9',
            field=models.CharField(blank=True, choices=[('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
    ]
