# Generated by Django 3.2.9 on 2023-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_account', '0002_auto_20230922_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='amount_to_credit9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='user_to_credit9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at1',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at10',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at2',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at3',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at4',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at5',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at6',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at7',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at8',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
        migrations.AlterField(
            model_name='closeaccount',
            name='cash_left_at9',
            field=models.CharField(blank=True, choices=[('Select cash left @', 'Select cash left @'), ('HEAD OFFICE', 'HEAD OFFICE'), ('DVLA BRANCH', 'DVLA BRANCH'), ('KEJETIA BRANCH', 'KEJETIA BRANCH'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM SUAME', 'MELCOM SUAME'), ('MELCOM TANOSO', 'MELCOM TANOSO')], default='Select cash left @', max_length=100),
        ),
    ]
