# Generated by Django 3.2.9 on 2023-09-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_account', '0003_auto_20230923_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount10',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='closeaccount',
            name='cash_left_at_amount9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
