# Generated by Django 5.2.11 on 2026-02-19 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("digital_address", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer_photos/"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport", "Passport"),
                            ("national_id", "National ID / Ghana Card"),
                            ("drivers_license", "Driver's License"),
                            ("voter_id", "Voter ID"),
                        ],
                        max_length=30,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=50)),
                (
                    "id_document_front",
                    models.ImageField(blank=True, null=True, upload_to="customer_ids/"),
                ),
                (
                    "id_document_back",
                    models.ImageField(blank=True, null=True, upload_to="customer_ids/"),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("kyc_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="core.company",
                    ),
                ),
                (
                    "kyc_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="customers.customer",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("company", "phone")},
            },
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Account"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "bank_or_network",
                    models.CharField(
                        help_text="Bank name (e.g. Ecobank, GCB) or mobile network (e.g. MTN, Vodafone).",
                        max_length=100,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_accounts",
                        to="core.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
