# Generated by Django 5.2.11 on 2026-02-19 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_requests",
                        to="core.company",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                            ("fee", "Fee"),
                            ("commission", "Commission"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("mobile_money", "Mobile Money"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("reversed", "Reversed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount after fees. Computed on save.",
                        max_digits=14,
                    ),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("description", models.TextField(blank=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Notes visible only to company staff."
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobileMoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN"),
                            ("vodafone", "Vodafone"),
                            ("airteltigo", "AirtelTigo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("send_money", "Send Money"),
                            ("receive_money", "Receive Money"),
                            ("cash_in", "Cash In"),
                            ("cash_out", "Cash Out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender_number", models.CharField(max_length=20)),
                ("receiver_number", models.CharField(blank=True, max_length=20)),
                ("momo_reference", models.CharField(blank=True, max_length=50)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momo_detail",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "d_200",
                    models.PositiveIntegerField(
                        default=0, verbose_name="200 GHS notes"
                    ),
                ),
                (
                    "d_100",
                    models.PositiveIntegerField(
                        default=0, verbose_name="100 GHS notes"
                    ),
                ),
                (
                    "d_50",
                    models.PositiveIntegerField(default=0, verbose_name="50 GHS notes"),
                ),
                (
                    "d_20",
                    models.PositiveIntegerField(default=0, verbose_name="20 GHS notes"),
                ),
                (
                    "d_10",
                    models.PositiveIntegerField(default=0, verbose_name="10 GHS notes"),
                ),
                (
                    "d_5",
                    models.PositiveIntegerField(default=0, verbose_name="5 GHS notes"),
                ),
                (
                    "d_2",
                    models.PositiveIntegerField(default=0, verbose_name="2 GHS coins"),
                ),
                (
                    "d_1",
                    models.PositiveIntegerField(default=0, verbose_name="1 GHS coins"),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_detail",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=255)),
                ("depositor_name", models.CharField(max_length=255)),
                ("slip_number", models.CharField(blank=True, max_length=50)),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="deposit_slips/"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_deposit_detail",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyClosing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "physical_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "mtn_ecash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "vodafone_ecash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "airteltigo_ecash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_ecash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "overage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shortage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_closings",
                        to="core.branch",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_closings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_closings",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("company", "closed_by", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProviderBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN"),
                            ("vodafone", "Vodafone"),
                            ("airtel", "Airtel"),
                            ("tigo", "Tigo"),
                            ("ecobank", "Ecobank"),
                            ("fidelity", "Fidelity"),
                            ("cal_bank", "Cal Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "starting_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The float amount the agent started with for this provider.",
                        max_digits=14,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current running balance for this provider.",
                        max_digits=14,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_balances",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "indexes": [
                    models.Index(
                        fields=["company", "user"],
                        name="transaction_company_a1e8f2_idx",
                    )
                ],
                "unique_together": {("company", "user", "provider")},
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["company", "created_at"], name="transaction_company_471ff8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["company", "status"], name="transaction_company_0ce1b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["company", "transaction_type"],
                name="transaction_company_d81ea8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference"], name="transaction_referen_923a88_idx"
            ),
        ),
    ]
