from django.urls import path
from . import views

urlpatterns = [
    path('admin_user/', views.get_admin),
    path('twilio_details/', views.get_twilio),
    path('agent_requests/', views.get_agent_requests),
    path('request_detail/<int:pk>/', views.request_detail),
    path('agent_request_approval/<int:id>/', views.approve_request),
    path('register_customer/', views.register_customer),
    path('agent_deposit_request/', views.user_deposit_request),
    path('customer_withdrawal/', views.customer_withdrawal),
    path('all_agents/', views.GetAllAgents.as_view()),
    path('all_customers/', views.GetAllCustomers.as_view()),
    path('customer_detail/<int:pk>/', views.customer_details),
    path('get_user_customers/<str:username>/', views.get_user_customers),
    path('agent_customer_summary/', views.agent_customers_summary),
    path('agent_deposit_request_summary/', views.deposit_request_summary),
    path('agents_customers_withdrawal_summary/', views.customer_withdrawal_summary),
    path('payments/', views.get_payments),
    path('make_payments/', views.make_payments),
    path('approve_payments/<int:id>/', views.approve_payment),
    path('payment_summary/', views.payment_summary),
    path('get_agent/<str:username>/', views.get_agent),
    path('payment_detail/<int:pk>/', views.payment_detail),
    path('get_customer/<str:name>/', views.get_customer),
    path('get_customer_by_phone/<str:phone>/', views.get_customer_by_phone),
    path('admin_accounts_started/', views.admin_accounts_started),
    path('admin_accounts_completed/', views.admin_accounts_completed),
    path('admin_accounts_started_lists/', views.admin_accounts_started_lists),
    path('admin_accounts_started_lists/', views.admin_accounts_completed_lists),
    path('user_customers/', views.user_customers),
    path('user_transaction_requests/<str:username>/', views.user_transaction_requests),
    path('user_transaction_payments/<str:username>/', views.user_transaction_payments),
    path('user_transaction_withdrawals/<str:username>/', views.user_transaction_withdrawals),

    path('register_customer_accounts/', views.register_customer_account),
    path('get_customer_accounts/',views.get_customer_accounts),
    path('customer_account_detail/<int:id>/',views.customer_account_detail),
    path('get_customer_account/<str:phone>/',views.get_customer_account),
    path('update_accounts/<int:id>/',views.update_accounts),
    path('admin_account_detail/<int:id>/',views.admin_account_detail),
    path('get_deposit_total/', views.get_deposit_total),
    path("get_payment_total/",views.get_payment_total),

    path("make_cash_at_payment/", views.make_bank_payment),
    path("add_withdraw_reference/", views.add_withdraw_reference),
    path("get_bank_payments/",views.get_user_bank_payments),
    path("get_withdraw_reference/",views.get_user_withdraw_reference),

    path("delete_user/<int:pk>/", views.user_delete),
    path("delete_customer/<int:pk>/", views.customer_delete),
    path("search_user_customers/",views.GetAllUserCustomers.as_view()),

    path('customer_request_deposit/', views.customer_deposit_request),
    path('get_your_customers_request/', views.get_your_customers_requests),
    path('get_customers_request/<str:phone>/',views.get_customers_requests),
    path('approve_customer_request/<int:id>/',views.approve_customer_request)
]
