# Generated by Django 3.2.9 on 2022-07-13 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAtBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_name', models.CharField(max_length=100)),
                ('teller_phone', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('d_200', models.IntegerField(blank=True, default=0)),
                ('d_100', models.IntegerField(blank=True, default=0)),
                ('d_50', models.IntegerField(blank=True, default=0)),
                ('d_20', models.IntegerField(blank=True, default=0)),
                ('d_10', models.IntegerField(blank=True, default=0)),
                ('d_5', models.IntegerField(blank=True, default=0)),
                ('d_2', models.IntegerField(blank=True, default=0)),
                ('d_1', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
